"""init schema

Revision ID: bc6557f717de
Revises:
Create Date: 2026-05-02 17:45:39.664731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc6557f717de"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chess_moves",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()")),
        sa.Column("game_uuid", sa.String(length=36)),
        sa.Column("game_url", sa.String()),
        sa.Column("archive_month", sa.String(length=7)),
        sa.Column("game_year", sa.Integer()),
        sa.Column("game_month", sa.Integer()),
        sa.Column("game_end_timestamp", sa.BigInteger()),
        sa.Column("game_end_datetime_utc", sa.DateTime(timezone=True)),
        sa.Column("end_hour_utc", sa.Integer()),
        sa.Column(
            "end_weekday_utc",
            sa.Enum(
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
                name="weekday_enum",
            ),
        ),
        sa.Column("rated", sa.Boolean()),
        sa.Column("rules", sa.String(length=50)),
        sa.Column(
            "time_class",
            sa.Enum(
                "bullet",
                "blitz",
                "rapid",
                "daily",
                name="time_class_enum",
                create_constraint=True,
            ),
        ),
        sa.Column("time_control_raw", sa.String(length=50)),
        sa.Column("time_control_base_seconds", sa.Integer()),
        sa.Column("time_control_increment_seconds", sa.Integer()),
        sa.Column("eco_url", sa.String()),
        sa.Column("eco_code", sa.String(length=5)),
        sa.Column("opening_name", sa.String(length=200)),
        sa.Column("white_username", sa.String(length=100)),
        sa.Column("black_username", sa.String(length=100)),
        sa.Column("white_rating", sa.Integer()),
        sa.Column("black_rating", sa.Integer()),
        sa.Column("rating_diff", sa.Integer()),
        sa.Column("white_accuracy", sa.Float()),
        sa.Column("black_accuracy", sa.Float()),
        sa.Column("ply_index", sa.Integer()),
        sa.Column("fullmove_number", sa.Integer()),
        sa.Column("side_to_move", sa.String(length=1)),
        sa.Column(
            "side_to_move_name",
            sa.Enum("white", "black", name="side_to_move_enum", create_constraint=True),
        ),
        sa.Column("san_move", sa.String(length=10)),
        sa.Column("uci_move", sa.String(length=10)),
        sa.Column(
            "piece_moved",
            sa.Enum(
                "pawn",
                "knight",
                "bishop",
                "rook",
                "queen",
                "king",
                name="piece_type_enum",
                create_constraint=True,
            ),
        ),
        sa.Column("from_square", sa.String(length=2)),
        sa.Column("to_square", sa.String(length=2)),
        sa.Column("is_capture", sa.Boolean()),
        sa.Column("is_check", sa.Boolean()),
        sa.Column("is_checkmate", sa.Boolean()),
        sa.Column("is_castling", sa.Boolean()),
        sa.Column("is_promotion", sa.Boolean()),
        sa.Column(
            "promotion_piece",
            sa.Enum(
                "queen",
                "rook",
                "bishop",
                "knight",
                name="promotion_piece_enum",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("board_fen_before", sa.String()),
        sa.Column("board_fen_after", sa.String()),
        sa.Column("active_color_before", sa.String(length=1)),
        sa.Column("castling_rights_before", sa.String(length=4)),
        sa.Column("en_passant_square_before", sa.String(length=2)),
        sa.Column("halfmove_clock_before", sa.Integer()),
        sa.Column("fullmove_number_before", sa.Integer()),
        sa.Column("legal_moves_count_before", sa.Integer()),
        sa.Column("total_piece_count_before", sa.Integer()),
        sa.Column("material_white_before", sa.Integer()),
        sa.Column("material_black_before", sa.Integer()),
        sa.Column("material_diff_before", sa.Integer()),
        sa.Column("non_pawn_material_white_before", sa.Integer()),
        sa.Column("non_pawn_material_black_before", sa.Integer()),
        sa.Column("non_pawn_material_diff_before", sa.Integer()),
        sa.Column("white_pawns_before", sa.Integer()),
        sa.Column("white_knights_before", sa.Integer()),
        sa.Column("white_bishops_before", sa.Integer()),
        sa.Column("white_rooks_before", sa.Integer()),
        sa.Column("white_queens_before", sa.Integer()),
        sa.Column("black_pawns_before", sa.Integer()),
        sa.Column("black_knights_before", sa.Integer()),
        sa.Column("black_bishops_before", sa.Integer()),
        sa.Column("black_rooks_before", sa.Integer()),
        sa.Column("black_queens_before", sa.Integer()),
        sa.Column("white_doubled_pawns_before", sa.Integer()),
        sa.Column("black_doubled_pawns_before", sa.Integer()),
        sa.Column("doubled_pawns_diff_before", sa.Integer()),
        sa.Column("white_isolated_pawns_before", sa.Integer()),
        sa.Column("black_isolated_pawns_before", sa.Integer()),
        sa.Column("isolated_pawns_diff_before", sa.Integer()),
        sa.Column("white_passed_pawns_before", sa.Integer()),
        sa.Column("black_passed_pawns_before", sa.Integer()),
        sa.Column("passed_pawns_diff_before", sa.Integer()),
        sa.Column("white_pawn_shield_score_before", sa.Float()),
        sa.Column("black_pawn_shield_score_before", sa.Float()),
        sa.Column("pawn_shield_diff_before", sa.Float()),
        sa.Column("white_king_tropism_before", sa.Float()),
        sa.Column("black_king_tropism_before", sa.Float()),
        sa.Column("king_tropism_diff_before", sa.Float()),
        sa.Column("white_can_castle_kingside_before", sa.Boolean()),
        sa.Column("white_can_castle_queenside_before", sa.Boolean()),
        sa.Column("black_can_castle_kingside_before", sa.Boolean()),
        sa.Column("black_can_castle_queenside_before", sa.Boolean()),
        sa.Column("in_check_before", sa.Boolean()),
        sa.Column("bishops_pair_white_before", sa.Boolean()),
        sa.Column("bishops_pair_black_before", sa.Boolean()),
        sa.Column("is_opening_phase", sa.Boolean()),
        sa.Column("is_middlegame_phase", sa.Boolean()),
        sa.Column("is_endgame_phase", sa.Boolean()),
        sa.Column("ply_bucket", sa.String(length=11)),
        sa.Column("white_clock_seconds_after", sa.Float()),
        sa.Column("black_clock_seconds_after", sa.Float()),
        sa.Column("clock_seconds_after_for_side_to_move", sa.Float()),
        sa.Column("side_to_move_clock_before", sa.Float()),
        sa.Column("time_spent_on_move_seconds", sa.Float()),
        sa.Column("clock_remaining_pct", sa.Float()),
        sa.Column("avg_time_spent_per_move_so_far", sa.Float()),
        sa.Column("is_in_time_trouble_30s", sa.Boolean()),
        sa.Column("side_to_move_rating", sa.Integer()),
        sa.Column("opponent_rating", sa.Integer()),
        sa.Column("side_to_move_rating_diff", sa.Integer()),
        sa.Column("result_raw", sa.String(length=100)),
        sa.Column("termination", sa.String(length=50)),
        sa.Column(
            "final_result_class",
            sa.Enum(
                "white_win",
                "black_win",
                "draw",
                name="result_class_enum",
                create_constraint=True,
            ),
        ),
        sa.Column("white_won_flag", sa.Integer()),
        sa.Column("black_won_flag", sa.Integer()),
        sa.Column("draw_flag", sa.Integer()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()")
        ),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_archive_month"),
        "chess_moves",
        ["archive_month"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_bishop_pair_result",
        "chess_moves",
        [
            "bishops_pair_white_before",
            "bishops_pair_black_before",
            "final_result_class",
        ],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_black_rating"),
        "chess_moves",
        ["black_rating"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_black_rating_result",
        "chess_moves",
        ["black_rating", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_capture_result",
        "chess_moves",
        ["is_capture", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_castling_result",
        "chess_moves",
        [
            "white_can_castle_kingside_before",
            "black_can_castle_kingside_before",
            "final_result_class",
        ],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_check_result",
        "chess_moves",
        ["is_check", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_eco_code"),
        "chess_moves",
        ["eco_code"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_eco_code_result",
        "chess_moves",
        ["eco_code", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_eco_ply",
        "chess_moves",
        ["eco_code", "ply_index"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_final_result_class"),
        "chess_moves",
        ["final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_game_ply",
        "chess_moves",
        ["game_uuid", "ply_index"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_game_uuid"),
        "chess_moves",
        ["game_uuid"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_game_year"),
        "chess_moves",
        ["game_year"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_material_counts",
        "chess_moves",
        ["material_white_before", "material_black_before", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_material_diff_result",
        "chess_moves",
        ["material_diff_before", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_phase_result",
        "chess_moves",
        ["is_opening_phase", "is_middlegame_phase", "is_endgame_phase"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_piece_count_result",
        "chess_moves",
        ["total_piece_count_before", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_ply_bucket_result",
        "chess_moves",
        ["ply_bucket", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_ply_index"),
        "chess_moves",
        ["ply_index"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_ratings_matchup",
        "chess_moves",
        ["white_rating", "black_rating", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_side_rating_diff",
        "chess_moves",
        ["side_to_move_rating", "side_to_move_rating_diff"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_time_class"),
        "chess_moves",
        ["time_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_time_class_result",
        "chess_moves",
        ["time_class", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_time_control_base_result",
        "chess_moves",
        ["time_control_base_seconds", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_time_trouble_result",
        "chess_moves",
        ["is_in_time_trouble_30s", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_timestamp",
        "chess_moves",
        ["game_end_timestamp"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_chess_moves_white_rating"),
        "chess_moves",
        ["white_rating"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_white_rating_result",
        "chess_moves",
        ["white_rating", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        "ix_chess_moves_year_month_result",
        "chess_moves",
        ["game_year", "game_month", "final_result_class"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chess_moves_year_month_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_white_rating_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_white_rating"), table_name="chess_moves", if_exists=True
    )
    op.drop_index("ix_chess_moves_timestamp", table_name="chess_moves", if_exists=True)
    op.drop_index(
        "ix_chess_moves_time_trouble_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_time_control_base_result",
        table_name="chess_moves",
        if_exists=True,
    )
    op.drop_index(
        "ix_chess_moves_time_class_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_time_class"), table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_side_rating_diff", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_ratings_matchup", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_ply_index"), table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_ply_bucket_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_piece_count_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_phase_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_material_diff_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_material_counts", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_game_year"), table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_game_uuid"), table_name="chess_moves", if_exists=True
    )
    op.drop_index("ix_chess_moves_game_ply", table_name="chess_moves", if_exists=True)
    op.drop_index(
        op.f("ix_chess_moves_final_result_class"),
        table_name="chess_moves",
        if_exists=True,
    )
    op.drop_index("ix_chess_moves_eco_ply", table_name="chess_moves", if_exists=True)
    op.drop_index(
        "ix_chess_moves_eco_code_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_eco_code"), table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_check_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_castling_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_capture_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_black_rating_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_black_rating"), table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        "ix_chess_moves_bishop_pair_result", table_name="chess_moves", if_exists=True
    )
    op.drop_index(
        op.f("ix_chess_moves_archive_month"), table_name="chess_moves", if_exists=True
    )
    op.drop_table("chess_moves", if_exists=True)
    op.execute("DROP TYPE IF EXISTS weekday_enum")
    op.execute("DROP TYPE IF EXISTS side_to_move_enum")
    op.execute("DROP TYPE IF EXISTS piece_type_enum")
    op.execute("DROP TYPE IF EXISTS promotion_piece_enum")
    op.execute("DROP TYPE IF EXISTS time_class_enum")
    op.execute("DROP TYPE IF EXISTS result_class_enum")
    # ### end Alembic commands ###
